### ISSUE TITLE
No module named 'vren'

### ISSUE THREAD

**Issue by Kirby13740** [kevinhuangxf/GeometrySticker#3]
Thanks for your great work! i dont find any package named 'vren'.i wonder if this is a pytorch version problem. Because of the cuda version limit of ssh platform, i only use pytorch 1.11.0.
![8f0e00c57938071456655493d0a1a3fb](https://github.com/user-attachments/assets/334679a4-2ea9-4fa8-b5ec-1dfaf48f7ed6)

**Comment by Kirby13740** [comment]
Thanks for your great work! Because of the cuda version limit of ssh platform, i only use pytorch 1.11.0.

**Comment by BigBang019** [comment]
```cd exp/ngp/models/csrc/ & pip install .```

**Comment by Kirby13740** [comment]
> `cd exp/ngp/models/csrc/ & pip install .`

The setup.py in the exp/ngp/models/csrc/ is for installing the package 'vren'. My problem is alright now , thank you!
